class GroupBy(object):
    max = "max"
    min = "min"
    sum = "sum"
    product = "product"
    first = "first"
    last = "last"
    count = "count"
    count_unique = "count_unique"
    avg = "avg"
    stdev = "stdev"
    median = "median"
    mode = "mode"