import column_selector/sliceconv
import column_selector/infos
import column_selector/collectinfo

export ColInfo
export toPyObj
export collectColumnSelectInfo
export doSliceConvert
export fromPyObjToDesiredInfos
