name: CodeCov
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: "3.10"
    - name: 'install dependencies'
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install codecov
        python -m pip install pytest-cov
        python -m pip install -r requirements.txt
    - name: Generate Report
      run: |
        python -m coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        verbose: true
        fail_ci_if_error: true # optional (default = false)

